export const copy = {
  brand: {
    name: 'PLAY//BACK',
    descriptor: 'AI GAME JUKEBOX',
    os: 'PLAY//BACK OS',
  },
  landing: {
    setupTitle: 'PLAY//BACK SETUP',
    setupMessage: 'A GAME IS WAITING.',
    titleLines: ['PLAY//BACK', 'PLAY//BACK', 'PLAY//BACK'],
    cta: 'INSERT COIN',
    previewTitle: 'GAME_PREVIEW.EXE',
    signal: 'SIGNAL: STABLE',
    time: 'LOCAL TIME 00:43',
  },
  intro: {
    windowTitle: 'INCOMING_SIGNAL.EXE',
    title: '2000s IS CALLING',
    progressLabel: 'CALL PROTOCOL',
    rounds: [
      {
        status: 'SIGNAL 01/03 · WAKE',
        caller: 'UNKNOWN ARCADE',
        lines: ['你醒了。', '现在是 2000 年。', '要接听这通来自旧互联网的电话吗？'],
        yes: 'YES / ANSWER',
        no: 'NO',
        errorTitle: 'SYSTEM ERROR 0x00',
        errorMessage: '拒绝失败：这条时间线还没有允许你挂断。',
      },
      {
        status: 'SIGNAL 02/03 · VERIFY',
        caller: 'THE LAST WEBMASTER',
        lines: ['信号稳定了。', '这里还有一间没有关门的游戏厅。', '你愿意进去见见最后的守门人吗？'],
        yes: 'YES / ENTER',
        no: 'NO',
        errorTitle: 'ACCESS DENIED',
        errorMessage: '返回路径已损坏。请继续向前，旧游戏厅正在等你。',
      },
      {
        status: 'SIGNAL 03/03 · CONNECT',
        caller: 'PLAY//BACK ARCHIVE',
        lines: ['最后确认一次。', '你的选择会唤醒一段被遗忘的游戏。', '准备连接 PLAY//BACK 吗？'],
        yes: 'YES / CONNECT',
        no: 'NO',
        errorTitle: 'FATAL: NO EXIT',
        errorMessage: '连接已锁定。只有完成这次呼叫，出口才会重新出现。',
      },
    ],
    errorReturn: 'RETURN',
    signalLabel: 'SIGNAL',
    ringTime: 'RING 00:08',
  },
  dialogue: {
    backgroundWords: ['LOST', 'IN THE', 'ARCHIVE'],
    speaker: 'WEBMASTER',
    speech: 'WTF?',
    greeting: ['你现在感觉怎么样？', '告诉我你今天想怎么玩。'],
    placeholder: '例如：只有10分钟，想玩塔防，不想太费脑……',
    defaultQuery: '只有10分钟，想玩塔防，不想太费脑',
    send: 'SEND',
    hint: 'ENTER TO SEND / ESC TO WAKE',
  },
  searching: {
    title: 'SEARCHING GAME ARCHIVE...',
    request: 'USER REQUEST',
    narrowing: ['50 GAMES', '18 MATCHES', '4 MATCHES'],
    archive: 'ARCHIVE_NODE_04',
    status: 'INDEXING OLD INTERNET',
  },
  game: {
    back: 'BACK',
    exitSystem: 'EXIT SYSTEM',
    shellTitle: 'GAME_004',
    suggested: 'WEBMASTER SUGGESTS',
    play: 'PLAY',
    pause: 'PAUSE',
    tryAnother: 'TRY ANOTHER',
    exit: 'EXIT',
    playing: 'GAME SIGNAL ACTIVE',
    ready: 'READY TO LOAD',
  },
  end: {
    title: 'SIGNAL LOST',
    time: '00:00',
    lines: ['连接正在断开。', '你该回到 2026 了。'],
    cta: 'WAKE UP',
  },
  system: {
    time: '00:43',
    online: 'ONLINE',
    enter: 'ENTER',
  },
} as const
