export const copy = {
  brand: {
    name: 'PLAY//BACK',
    descriptor: 'AI GAME JUKEBOX',
    os: 'PLAY//BACK OS',
  },
  landing: {
    setupTitle: 'PLAY//BACK SETUP',
    setupMessage: 'A GAME IS WAITING.',
    titleLines: ['PLAY//BACK', 'PLAY//BACK', 'PLAY//BACK'],
    cta: 'INSERT COIN',
    previewTitle: 'GAME_PREVIEW.EXE',
    signal: 'SIGNAL: STABLE',
    time: 'LOCAL TIME 00:43',
  },
  intro: {
    windowTitle: 'INCOMING_SIGNAL.EXE',
    title: '2000s IS CALLING',
    status: 'INCOMING SIGNAL...',
    caller: 'UNKNOWN ARCADE',
    lines: ['你醒了。', '现在是 2000 年。', '有人还守着这间游戏厅。'],
    answer: 'ANSWER',
    decline: 'DECLINE',
    declineTitle: 'CALLER NOT FOUND',
    declineMessage: 'DECLINE IS NOT AVAILABLE IN THIS TIMELINE.',
    signalStrength: 'SIGNAL 04/04',
    ringTime: 'RING 00:08',
  },
  dialogue: {
    backgroundWords: ['LOST', 'IN THE', 'ARCHIVE'],
    speaker: 'WEBMASTER',
    speech: 'WTF?',
    greeting: ['你现在感觉怎么样？', '告诉我你今天想怎么玩。'],
    placeholder: '例如：只有10分钟，想玩塔防，不想太费脑……',
    defaultQuery: '只有10分钟，想玩塔防，不想太费脑',
    send: 'SEND',
    hint: 'ENTER TO SEND / ESC TO WAKE',
  },
  searching: {
    title: 'SEARCHING GAME ARCHIVE...',
    request: 'USER REQUEST',
    narrowing: ['50 GAMES', '18 MATCHES', '4 MATCHES'],
    archive: 'ARCHIVE_NODE_04',
    status: 'INDEXING OLD INTERNET',
  },
  game: {
    back: 'BACK',
    exitSystem: 'EXIT SYSTEM',
    shellTitle: 'GAME_004',
    suggested: 'WEBMASTER SUGGESTS',
    play: 'PLAY',
    pause: 'PAUSE',
    tryAnother: 'TRY ANOTHER',
    exit: 'EXIT',
    playing: 'GAME SIGNAL ACTIVE',
    ready: 'READY TO LOAD',
  },
  end: {
    title: 'SIGNAL LOST',
    time: '00:00',
    lines: ['连接正在断开。', '你该回到 2026 了。'],
    cta: 'WAKE UP',
  },
  system: {
    time: '00:43',
    online: 'ONLINE',
    enter: 'ENTER',
  },
} as const
